### ISSUE TITLE
Missing OnsetsFramesWavinput

### ISSUE THREAD

**Issue by chinahgf** [BShakhovsky/PianoTranscription_Android#1]
Hi 
Missing OnsetsFramesWavinput class

**Comment by BShakhovsky** [comment]
Hi,
 
Yes, I could not upload this TFLite model because its size is around 100 MB, and GitHub would not allow me to upload it to my repository. You can download it from Magenta's repository here:
https://github.com/magenta/magenta/tree/main/magenta/models/onsets_frames_transcription/realtime
There are three models, and I used the full model (__*onsets_frames_wavinput.tflite*__).  You should put it in the following folder:
`app/src/main/ml/`
Or, if you are using Android Studio, you can import the model, and it will be placed in the correct folder automatically.

**Comment by chinahgf** [comment]
Okay, I get it.
Thanks
